### PR TITLE
Update 5eb8d24b-d660-42e5-bbea-47a659bb0827 - Main GVAR.gvar

### PR DESCRIPTION
**Pull request by nerdsanddragons**
New or updated features

Updated
-walls Can be now added one at a time
New
-deletewalls (wall) - Allows you to delete a individual wall

New Features
-object (location):(object) - Adds an object to the map. Some objects can be placed over multiple squares.
!map objectlist to view available objects.
-deleteobject (location):(object) - Deletes the specified object from the map

-savetoken (tokenName):(shortcode) - Saves a token to your mapTokens uvar
-deletetoken (tokenName) - Deletes a token you have saved
-loadtoken (tokenName) - Allows you to load a saved token to a target. Example: !map -t go1 -loadtoken goblin
!map tokenlist - Allows you to see a list of all your saved tokens

Deleted
-savewalls - Code no longer functions properly because of the updated -walls code. Need to revamp -savemap and -loadmap

Updated all info in the help menus

### CODE REVIEW

**Comment by nerdsanddragons** [comment]
Commit e01f601c0f844f2f74eb2889393c3f3fd1747297
Ignore

**Comment by nerdsanddragons** [comment]
So commit e01f601c0f844f2f74eb2889393c3f3fd1747297 Has the code for the new -savemap but made a mistake in it. The most recent commit fixed that mistake as well as I added the new -loadmap code

**Comment by nerdsanddragons** [comment]
So commit e01f601c0f844f2f74eb2889393c3f3fd1747297 Has the code for the new -savemap but made a mistake in it. The most recent commit fixed that mistake as well as I added the new -loadmap code

**Comment by Croebh** [comment]
Manually merged in https://github.com/Croebh/Avrae-Customizations/commit/be093c91100a6af9ca693f1a2ff01592e52258a4

**Pull request closed without merging**
